package wasi:webrtc-data-channels@0.0.1;

interface types {
  type error = string;

  resource peer-connection {
    constructor();
    create-data-channel: func(label: string) -> result<data-channel, error>;
  }

  resource data-channel {
    send: async func(data: list<u8>) -> result<_, error>;
    receive: async func() -> result<list<u8>, error>;
  }
}

world imports {
  import types;
}